# Generated by Django 4.1.6 on 2023-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
