# Generated by Django 4.1.6 on 2023-02-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password_hash',
        ),
    ]
