# Generated by Django 4.1.6 on 2023-02-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_password_customer_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password_hash',
            new_name='password',
        ),
    ]
