# Generated by Django 4.1.6 on 2023-02-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_total',
            new_name='price',
        ),
    ]
