# Generated by Django 4.1.6 on 2023-03-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_item_total_orderitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
