# Generated by Django 4.1.6 on 2023-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
